// Generated by scripts/fetch_images.py from plants.json and images/manifest.json.
// Do not edit by hand.
window.PLANT_DATA = {
 "plants": [
  {
   "id": "acer-palmatum",
   "botanical": "Acer palmatum",
   "common": "Japanese maple",
   "botanicalAccept": [],
   "commonAccept": [],
   "search": {
    "names": [
     "Acer palmatum"
    ],
    "parts": {},
    "files": [
     {
      "part": "Leaves",
      "title": "Leaves of Acer palmatum (2005).jpg"
     },
     {
      "part": "Flowers",
      "title": "Acer palmatum flowers 001.JPG"
     },
     {
      "part": "Bark",
      "title": "Acer palmatum bark 1 LR.jpg"
     },
     {
      "part": "Fruit",
      "title": "Acer palmatum subsp. amoenum in Hackfalls Arboretum (4).jpg"
     },
     {
      "part": "Habit",
      "title": "Hortus Haren d.j.b 20.jpg"
     }
    ]
   }
  },
  {
   "id": "heuchera",
   "botanical": "Heuchera sp.",
   "common": "coral bells",
   "botanicalAccept": [
    "heuchera",
    "heuchera sp",
    "heuchera spp",
    "heuchera species"
   ],
   "commonAccept": [
    "coralbells",
    "alumroot",
    "coral bell"
   ],
   "search": {
    "names": [
     "Heuchera sanguinea",
     "Heuchera micrantha",
     "Heuchera"
    ],
    "parts": {
     "Flowers": "flowers",
     "Leaves": "leaves",
     "Habit": "plant",
     "Close-up": "inflorescence"
    }
   }
  },
  {
   "id": "arbutus-unedo",
   "botanical": "Arbutus unedo",
   "common": "strawberry tree",
   "botanicalAccept": [],
   "commonAccept": [],
   "search": {
    "names": [
     "Arbutus unedo"
    ],
    "parts": {
     "Flowers": "flowers",
     "Fruit": "fruit",
     "Leaves": "leaves",
     "Bark": "bark",
     "Habit": "tree"
    }
   }
  },
  {
   "id": "salvia-rosmarinus",
   "botanical": "Salvia rosmarinus",
   "common": "rosemary",
   "botanicalAccept": [
    "rosmarinus officinalis"
   ],
   "commonAccept": [],
   "search": {
    "names": [
     "Rosmarinus officinalis",
     "Salvia rosmarinus"
    ],
    "parts": {
     "Flowers": "flowers",
     "Leaves": "leaves",
     "Habit": "shrub",
     "Close-up": "flower"
    }
   }
  },
  {
   "id": "ginkgo-biloba",
   "botanical": "Ginkgo biloba",
   "common": "ginkgo",
   "botanicalAccept": [
    "gingko biloba"
   ],
   "commonAccept": [
    "maidenhair tree",
    "gingko"
   ],
   "search": {
    "names": [
     "Ginkgo biloba"
    ],
    "parts": {},
    "files": [
     {
      "part": "Leaves",
      "title": "Ginkgo biloba - Fallen leaves - 2024 Pisa.jpg"
     },
     {
      "part": "Fruit",
      "title": "Ginkgo biloba seeds of Hongokuji no Ohatsuki Icho.jpg"
     },
     {
      "part": "Bark",
      "title": "Ginkgo Tree Ginkgo biloba Trunk Bark 2000px.jpg"
     },
     {
      "part": "Habit",
      "title": "Ginkgo tree in Green-Wood Cemetery (23299p).jpg"
     },
     {
      "part": "Autumn",
      "title": "A golden Ginkgo biloba in autumn.jpg"
     }
    ]
   }
  },
  {
   "id": "cercis-occidentalis",
   "botanical": "Cercis occidentalis",
   "common": "Western redbud",
   "botanicalAccept": [],
   "commonAccept": [
    "california redbud",
    "redbud"
   ],
   "search": {
    "names": [
     "Cercis occidentalis"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Cercis occidentalis flowers 2004-03-10.jpg"
     },
     {
      "part": "Leaves",
      "title": "Cercis occidentalis, California.jpg"
     },
     {
      "part": "Seed pods",
      "title": "H20150416-0002—Cercis occidentalis—RPBG (17051649770).jpg"
     },
     {
      "part": "Habit",
      "title": "Western red bud near Briceburg 2019-04-14.jpg"
     },
     {
      "part": "Bark",
      "title": "Cercis occidentalis bark.jpg"
     }
    ]
   }
  },
  {
   "id": "juncus",
   "botanical": "Juncus sp.",
   "common": "rush",
   "botanicalAccept": [
    "juncus",
    "juncus sp",
    "juncus spp",
    "juncus species",
    "juncus effusus",
    "juncus patens"
   ],
   "commonAccept": [
    "rushes",
    "common rush",
    "soft rush"
   ],
   "search": {
    "names": [
     "Juncus effusus",
     "Juncus patens"
    ],
    "parts": {
     "Habit": "plant",
     "Inflorescence": "inflorescence",
     "Stems": "stems",
     "Close-up": "flowers"
    }
   }
  },
  {
   "id": "cotinus-coggygria",
   "botanical": "Cotinus coggygria",
   "common": "smoke tree",
   "botanicalAccept": [],
   "commonAccept": [
    "smokebush",
    "smoke bush",
    "smoketree",
    "european smoketree",
    "european smoke tree"
   ],
   "search": {
    "names": [
     "Cotinus coggygria"
    ],
    "parts": {
     "Flowers": "inflorescence",
     "Leaves": "leaves",
     "Habit": "shrub",
     "Autumn": "autumn"
    }
   }
  },
  {
   "id": "salvia-spathacea",
   "botanical": "Salvia spathacea",
   "common": "hummingbird sage",
   "botanicalAccept": [],
   "commonAccept": [
    "pitcher sage"
   ],
   "search": {
    "names": [
     "Salvia spathacea"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Salvia spathacea.JPG"
     },
     {
      "part": "Leaves",
      "title": "Salvia spathacea - Flickr - peganum (3).jpg"
     },
     {
      "part": "Habit",
      "title": "Salvia spathacea - Descanso Gardens - La Cañada Flintridge, CA - DSC00853.jpg"
     },
     {
      "part": "Close-up",
      "title": "SAGE, HUMMINGBIRD (salvia spathacea) (4-5-07) 2- canet (535475331).jpg"
     },
     {
      "part": "Plant",
      "title": "Salvia spathacea - Flickr - peganum (1).jpg"
     }
    ]
   }
  },
  {
   "id": "heteromeles-arbutifolia",
   "botanical": "Heteromeles arbutifolia",
   "common": "toyon",
   "botanicalAccept": [],
   "commonAccept": [
    "christmas berry",
    "california holly",
    "christmasberry"
   ],
   "search": {
    "names": [
     "Heteromeles arbutifolia"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Heteromeles arbutifolia flowers Wildcat Canyon Preserve 8.jpg"
     },
     {
      "part": "Berries",
      "title": "TOYON (heteromeles arbutifolia) (3-24-07) canet (535371030).jpg"
     },
     {
      "part": "Leaves",
      "title": "Heteromeles arbutifolia 2.jpg"
     },
     {
      "part": "Habit",
      "title": "Toyon (Heteromeles arbutifolia) Tree (31892009192).jpg"
     }
    ]
   }
  },
  {
   "id": "baccharis-pilularis",
   "botanical": "Baccharis pilularis",
   "common": "coyote brush",
   "botanicalAccept": [],
   "commonAccept": [
    "coyote bush",
    "chaparral broom",
    "coyotebrush"
   ],
   "search": {
    "names": [
     "Baccharis pilularis"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Chaparral Coyote Brush (Baccharis pilularis ssp. consanguinea), Photo 578271695.jpg"
     },
     {
      "part": "Leaves",
      "title": "Baccharis pilularis.jpg"
     },
     {
      "part": "Habit",
      "title": "Baccharis pilularis kz6.jpg"
     },
     {
      "part": "Seeds",
      "title": "201211 208 San Diego Botanic Gdn - Natural Coastal Habitat, Baccharis pilularis Coyote Bush, a female plant in seed.jpg"
     }
    ]
   }
  },
  {
   "id": "vitis-californica-rogers-red",
   "botanical": "Vitis californica 'Roger's Red'",
   "common": "Roger's Red California grape",
   "botanicalAccept": [
    "vitis californica rogers red",
    "vitis californica cv rogers red",
    "vitis rogers red"
   ],
   "botanicalPartial": [
    "vitis californica",
    "vitis"
   ],
   "commonAccept": [
    "rogers red grape",
    "rogers red",
    "rogers red california wild grape",
    "california grape rogers red",
    "california wild grape rogers red"
   ],
   "note": "Photos may show the straight species Vitis californica; 'Roger's Red' is the selection with brilliant red fall color.",
   "search": {
    "names": [
     "Vitis californica 'Roger's Red'",
     "Vitis californica Roger's Red",
     "Vitis californica"
    ],
    "parts": {
     "Leaves": "leaves",
     "Fruit": "grapes",
     "Habit": "vine",
     "Autumn": "autumn",
     "Bark": "bark"
    }
   }
  },
  {
   "id": "plumbago-auriculata",
   "botanical": "Plumbago auriculata",
   "common": "Cape plumbago",
   "botanicalAccept": [
    "plumbago capensis"
   ],
   "commonAccept": [
    "plumbago",
    "cape leadwort",
    "leadwort",
    "blue plumbago"
   ],
   "search": {
    "names": [
     "Plumbago auriculata"
    ],
    "parts": {
     "Flowers": "flowers",
     "Leaves": "leaves",
     "Habit": "shrub",
     "Close-up": "flower"
    }
   }
  },
  {
   "id": "melianthus-major",
   "botanical": "Melianthus major",
   "common": "honey bush",
   "botanicalAccept": [],
   "commonAccept": [
    "honeybush",
    "giant honey flower",
    "honey flower",
    "giant honeybush"
   ],
   "search": {
    "names": [
     "Melianthus major"
    ],
    "parts": {},
    "files": [
     {
      "part": "Leaves",
      "title": "Melianthus major Leaf Top 3008px.jpg"
     },
     {
      "part": "Flowers",
      "title": "Giant Honey Flower Melianthus major Newark Park Ozleworth Gloucestershire England.jpg"
     },
     {
      "part": "Habit",
      "title": "Melianthus major - Orto botanico - Rome, Italy - DSC00098.jpg"
     },
     {
      "part": "Close-up",
      "title": "Melianthus major 2.jpg"
     }
    ]
   }
  },
  {
   "id": "diplacus-eleanor",
   "botanical": "Diplacus 'Eleanor'",
   "common": "Eleanor's monkeyflower",
   "botanicalAccept": [
    "diplacus eleanor",
    "mimulus eleanor",
    "diplacus cv eleanor"
   ],
   "botanicalPartial": [
    "diplacus",
    "mimulus",
    "diplacus aurantiacus",
    "mimulus aurantiacus"
   ],
   "commonAccept": [
    "eleanor monkeyflower",
    "eleanor monkey flower",
    "eleanors monkey flower",
    "monkeyflower eleanor"
   ],
   "note": "'Eleanor' is a hybrid monkeyflower with pale cream-yellow flowers; photos may show related Diplacus hybrids or species.",
   "search": {
    "names": [
     "Diplacus 'Eleanor'",
     "Mimulus 'Eleanor'",
     "Diplacus hybrid",
     "Diplacus aurantiacus"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Mimulus pamela.jpg"
     },
     {
      "part": "Habit",
      "title": "Mimulus trish.jpg"
     },
     {
      "part": "Close-up",
      "title": "Sticky Monkey-Flower - Diplacus aurantiacus (43440614412).jpg"
     },
     {
      "part": "Plant",
      "title": "Sticky Monkey-Flower - Diplacus aurantiacus (42902155992).jpg"
     }
    ]
   }
  },
  {
   "id": "nepeta-walkers-low",
   "botanical": "Nepeta × faassenii 'Walker's Low'",
   "common": "Walker's Low catmint",
   "botanicalAccept": [
    "nepeta x faassenii walkers low",
    "nepeta faassenii walkers low",
    "nepeta walkers low",
    "nepeta x faassenii cv walkers low"
   ],
   "botanicalPartial": [
    "nepeta x faassenii",
    "nepeta faassenii",
    "nepeta"
   ],
   "commonAccept": [
    "walkers low catmint",
    "catmint walkers low",
    "walkers low",
    "catmint"
   ],
   "search": {
    "names": [
     "Nepeta 'Walker's Low'",
     "Nepeta Walker's Low",
     "Nepeta × faassenii",
     "Nepeta faassenii"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Nepeta x faasenii Walkers Low 2zz.jpg"
     },
     {
      "part": "Leaves",
      "title": "Nepetaxfaassenii.jpg"
     },
     {
      "part": "Habit",
      "title": "Nepeta faassenii catmint Easton Lodge Gardens walled garden Little Easton Essex England 01.jpg"
     },
     {
      "part": "Close-up",
      "title": "Nepeta x faassenii Walkers Low 2zz.jpg"
     }
    ]
   }
  },
  {
   "id": "teucrium-fruticans",
   "botanical": "Teucrium fruticans",
   "common": "shrubby germander",
   "botanicalAccept": [],
   "commonAccept": [
    "bush germander",
    "tree germander",
    "germander",
    "silver germander"
   ],
   "search": {
    "names": [
     "Teucrium fruticans"
    ],
    "parts": {
     "Flowers": "flowers",
     "Leaves": "leaves",
     "Habit": "shrub",
     "Close-up": "flower"
    }
   }
  },
  {
   "id": "oenothera-lindheimeri",
   "botanical": "Oenothera lindheimeri",
   "common": "gaura",
   "botanicalAccept": [
    "gaura lindheimeri"
   ],
   "commonAccept": [
    "whirling butterflies",
    "lindheimers beeblossom",
    "beeblossom",
    "bee blossom",
    "wand flower",
    "wandflower"
   ],
   "search": {
    "names": [
     "Gaura lindheimeri",
     "Oenothera lindheimeri"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Gaura lindheimeri flower.JPG"
     },
     {
      "part": "Leaves",
      "title": "Starr-110307-2543-Gaura lindheimeri-leaves-Kula Botanical Garden-Maui (24984958231).jpg"
     },
     {
      "part": "Habit",
      "title": "Gaura lindheimeri A.jpg"
     },
     {
      "part": "Flower stem",
      "title": "Gaura lindheimeri Whirling Butterflies 1zz.jpg"
     },
     {
      "part": "Close-up",
      "title": "Gaura lindheimeri.jpg"
     }
    ]
   }
  },
  {
   "id": "salvia-apiana",
   "botanical": "Salvia apiana",
   "common": "white sage",
   "botanicalAccept": [],
   "commonAccept": [
    "bee sage",
    "sacred sage"
   ],
   "search": {
    "names": [
     "Salvia apiana"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Salvia apiana 3.jpg"
     },
     {
      "part": "Leaves",
      "title": "J20161110-0061—Salvia apiana—RPBG—DxO (38341671812).jpg"
     },
     {
      "part": "Habit",
      "title": "Salvia apiana 1c.JPG"
     },
     {
      "part": "Rosette",
      "title": "Salvia apiana 001 — briweldon.jpg"
     }
    ]
   }
  },
  {
   "id": "romneya-coulteri",
   "botanical": "Romneya coulteri",
   "common": "Matilija poppy",
   "botanicalAccept": [],
   "commonAccept": [
    "matilija",
    "fried egg plant",
    "fried egg flower",
    "coulters matilija poppy"
   ],
   "search": {
    "names": [
     "Romneya coulteri"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Romneya coulteri ABL3.JPG"
     },
     {
      "part": "Leaves",
      "title": "Romneya coulteri Branche feuillue Jardin des Plantes.jpg"
     },
     {
      "part": "Habit",
      "title": "Romneya coulteri HRM1.jpg"
     },
     {
      "part": "Buds",
      "title": "Matilija Poppy, Rhomneya coulteri - Flickr - theforestprimeval.jpg"
     },
     {
      "part": "Close-up",
      "title": "Romneya-coulteri-flower.jpg"
     }
    ]
   }
  },
  {
   "id": "scabiosa-columbaria",
   "botanical": "Scabiosa columbaria",
   "common": "scabiosa",
   "botanicalAccept": [],
   "commonAccept": [
    "pincushion flower",
    "small scabious",
    "dove pincushions",
    "pincushion"
   ],
   "search": {
    "names": [
     "Scabiosa columbaria"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Scabiosa columbaria0.jpg"
     },
     {
      "part": "Leaves",
      "title": "Scabiosa columbaria Driakiew gołębia 2020-08-07 04.jpg"
     },
     {
      "part": "Basal rosette",
      "title": "GBIF 2888802 5995451240.jpg"
     },
     {
      "part": "Habit",
      "title": "Small scabious (Scabiosa columbaria) - geograph.org.uk - 5489110.jpg"
     },
     {
      "part": "Close-up",
      "title": "Scabiosa columbaria flower.jpg"
     }
    ]
   }
  },
  {
   "id": "salvia-pozo-blue",
   "botanical": "Salvia 'Pozo Blue'",
   "common": "Pozo blue sage",
   "botanicalAccept": [
    "salvia pozo blue",
    "salvia cv pozo blue",
    "salvia clevelandii pozo blue"
   ],
   "botanicalPartial": [
    "salvia",
    "salvia clevelandii"
   ],
   "commonAccept": [
    "pozo blue",
    "pozo blue salvia",
    "gray musk sage"
   ],
   "note": "'Pozo Blue' is a hybrid of Salvia clevelandii and S. leucophylla; photos may show the Cleveland sage parent.",
   "search": {
    "names": [
     "Salvia 'Pozo Blue'",
     "Salvia Pozo Blue",
     "Salvia clevelandii"
    ],
    "parts": {
     "Flowers": "flowers",
     "Leaves": "leaves",
     "Habit": "plant",
     "Close-up": "flower"
    }
   }
  },
  {
   "id": "salvia-mellifera",
   "botanical": "Salvia mellifera",
   "common": "black sage",
   "botanicalAccept": [
    "salvia melifera"
   ],
   "commonAccept": [],
   "note": "Spelled 'Salvia melifera' on the class list; 'mellifera' (two l's) is the accepted spelling. Both are accepted here.",
   "search": {
    "names": [
     "Salvia mellifera"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Salvia mellifera flowers 2003-03-12.jpg"
     },
     {
      "part": "Leaves",
      "title": "File--i-Salvia mellifera-i--br--Mint family (Lamiaceae) (f5e142ee-c13e-5458-2b5f-492e1394435f).jpg"
     },
     {
      "part": "Habit",
      "title": "Salvia mellifera kz01.jpg"
     },
     {
      "part": "Close-up",
      "title": "Black Sage (Salvia mellifera) (2322427355).jpg"
     }
    ]
   }
  },
  {
   "id": "salvia-yangii",
   "botanical": "Salvia yangii",
   "common": "Russian sage",
   "botanicalAccept": [
    "perovskia atriplicifolia",
    "perovskia"
   ],
   "commonAccept": [
    "perovskia"
   ],
   "search": {
    "names": [
     "Perovskia atriplicifolia",
     "Salvia yangii"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Mint and Perovskia (8009159019).jpg"
     },
     {
      "part": "Leaves",
      "title": "Perovskia atriplicifolia leave.jpg"
     },
     {
      "part": "Habit",
      "title": "Gommern, der Heidegarten, Perovskia atriplicifolia.jpg"
     },
     {
      "part": "Flower spikes",
      "title": "20170719Perovskia atriplicifolia3.jpg"
     },
     {
      "part": "Close-up",
      "title": "Perovskia-atriplicifolia-2.jpg"
     }
    ]
   }
  },
  {
   "id": "verbena-bonariensis",
   "botanical": "Verbena bonariensis",
   "common": "tall vervain",
   "botanicalAccept": [],
   "commonAccept": [
    "purpletop vervain",
    "purple top vervain",
    "argentinian vervain",
    "brazilian vervain",
    "tall verbena",
    "purpletop verbena"
   ],
   "search": {
    "names": [
     "Verbena bonariensis"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Verbena bonariensis, bloeiwijze. 28-08-2021. (d.j.b) 01.jpg"
     },
     {
      "part": "Leaves",
      "title": "Verbena bonariensis 'Purple top' (Verbenaceae) leaves.JPG"
     },
     {
      "part": "Habit",
      "title": "'Verbena bonariensis' in the Walled Garden at Goodnestone Park Kent England 1.jpg"
     },
     {
      "part": "Stem",
      "title": "Verbena bonariensis stem (02).jpeg"
     }
    ]
   }
  },
  {
   "id": "anigozanthos",
   "botanical": "Anigozanthos sp.",
   "common": "kangaroo paw",
   "botanicalAccept": [
    "anigozanthos",
    "anigozanthos sp",
    "anigozanthos spp",
    "anigozanthos species",
    "anigozanthos flavidus"
   ],
   "commonAccept": [
    "kangaroo paws",
    "kangaroopaw"
   ],
   "search": {
    "names": [
     "Anigozanthos flavidus",
     "Anigozanthos",
     "Anigozanthos manglesii"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Starr-090430-6847-Anigozanthos flavidus-flowers-Enchanting Floral Gardens of Kula-Maui (24322840644).jpg"
     },
     {
      "part": "Leaves",
      "title": "Anigozanthos rufus 'Red Kangaroo Paw' (Haemodoraceae) leaves.JPG"
     },
     {
      "part": "Habit",
      "title": "Anigozanthos flavidus HRM.jpg"
     },
     {
      "part": "Close-up",
      "title": "Anigozanthos flavidus flower stalk - HNT.jpg"
     }
    ]
   }
  },
  {
   "id": "eschscholzia-californica",
   "botanical": "Eschscholzia californica",
   "common": "California poppy",
   "botanicalAccept": [
    "escholzia californica",
    "eschscholtzia californica"
   ],
   "commonAccept": [
    "golden poppy",
    "cup of gold",
    "california golden poppy"
   ],
   "search": {
    "names": [
     "Eschscholzia californica"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Bright Orange California Poppy.jpg"
     },
     {
      "part": "Leaves",
      "title": "Eschscholzia californica (California poppy) florescence and leaves next to Calystegia soldanella (beach morningglory) leaves (7184134380).jpg"
     },
     {
      "part": "Habit",
      "title": "Eschscholzia californica 'alifornian poppy' (Papaveraceae) plant and leaves.JPG"
     },
     {
      "part": "Seeds",
      "title": "Eschscholzia californica seeds.jpg"
     },
     {
      "part": "Mass bloom",
      "title": "California Poppies blossom - Antelope Valley California Poppy Reserve4.jpg"
     }
    ]
   }
  },
  {
   "id": "nemophila-menziesii",
   "botanical": "Nemophila menziesii",
   "common": "baby blue eyes",
   "botanicalAccept": [],
   "commonAccept": [
    "baby blue-eyes",
    "baby blueeyes"
   ],
   "search": {
    "names": [
     "Nemophila menziesii"
    ],
    "parts": {},
    "files": [
     {
      "part": "Flowers",
      "title": "Flowers of Nemophila menziesii in Nokonoshima Island Park.jpg"
     },
     {
      "part": "Leaves",
      "title": "Baby Blue Eyes Scanography.jpg"
     },
     {
      "part": "Habit",
      "title": "Baby Blue Eyes, Shell Creek (49621100262).jpg"
     },
     {
      "part": "Close-up",
      "title": "Nemophila menziesii.jpg"
     }
    ]
   }
  },
  {
   "id": "layia-platyglossa",
   "botanical": "Layia platyglossa",
   "common": "tidy tips",
   "botanicalAccept": [],
   "commonAccept": [
    "tidytips",
    "coastal tidytips",
    "coastal tidy tips",
    "tidy tip"
   ],
   "search": {
    "names": [
     "Layia platyglossa"
    ],
    "parts": {
     "Flowers": "flower",
     "Leaves": "leaves",
     "Habit": "plant",
     "Close-up": "flowers"
    }
   }
  }
 ],
 "images": {
  "acer-palmatum": [
   {
    "part": "Leaves",
    "title": "Leaves of Acer palmatum (2005).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Leaves_of_Acer_palmatum_(2005).jpg",
    "author": "Tomomarusan",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "file": "acer-palmatum/01-leaves.jpg"
   },
   {
    "part": "Flowers",
    "title": "Acer palmatum flowers 001.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Acer_palmatum_flowers_001.JPG",
    "author": "User:SB_Johnny",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "file": "acer-palmatum/02-flowers.jpg"
   },
   {
    "part": "Bark",
    "title": "Acer palmatum bark 1 LR.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Acer_palmatum_bark_1_LR.jpg",
    "author": "PumpkinSky",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "acer-palmatum/03-bark.jpg"
   },
   {
    "part": "Fruit",
    "title": "Acer palmatum subsp. amoenum in Hackfalls Arboretum (4).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Acer_palmatum_subsp._amoenum_in_Hackfalls_Arboretum_(4).jpg",
    "author": "Krzysztof Golik",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "acer-palmatum/04-fruit.jpg"
   },
   {
    "part": "Habit",
    "title": "Hortus Haren d.j.b 20.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Hortus_Haren_d.j.b_20.jpg",
    "author": "Dominicus Johannes Bergsma",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "acer-palmatum/05-habit.jpg"
   }
  ],
  "heuchera": [
   {
    "part": "Flowers",
    "title": "Heuchera sanguinea flowers.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Heuchera_sanguinea_flowers.jpg",
    "author": "Neelix",
    "license": "Public domain",
    "licenseUrl": "",
    "file": "heuchera/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Heuchera micrantha 1584.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Heuchera_micrantha_1584.JPG",
    "author": "Walter Siegmund (talk)",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "heuchera/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "(MHNT) Heuchera sanguinea - immature inflorescence.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:(MHNT)_Heuchera_sanguinea_-_immature_inflorescence.jpg",
    "author": "Didier Descouens",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "heuchera/03-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "(MHNT) Heuchera micrantha flowers.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:(MHNT)_Heuchera_micrantha_flowers.jpg",
    "author": "Didier Descouens",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "heuchera/04-close-up.jpg"
   }
  ],
  "arbutus-unedo": [
   {
    "part": "Flowers",
    "title": "Arbutus unedo Flowers Fruits Closeup DehesaBoyaldePuertollano.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Arbutus_unedo_Flowers_Fruits_Closeup_DehesaBoyaldePuertollano.jpg",
    "author": "Javier martin",
    "license": "Public domain",
    "licenseUrl": "",
    "file": "arbutus-unedo/01-flowers.jpg"
   },
   {
    "part": "Fruit",
    "title": "Strawberry tree (Arbutus unedo) fruit and leaves on a rainy day, Parque Florestal de Monsanto, Lisbon, Portugal julesvernex2.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Strawberry_tree_(Arbutus_unedo)_fruit_and_leaves_on_a_rainy_day,_Parque_Florestal_de_Monsanto,_Lisbon,_Portugal_julesvernex2.jpg",
    "author": "Jules Verne Times Two",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "arbutus-unedo/02-fruit.jpg"
   },
   {
    "part": "Leaves",
    "title": "Arbutus unedo leaves and fruit.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Arbutus_unedo_leaves_and_fruit.jpg",
    "author": "Imnulls",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "file": "arbutus-unedo/03-leaves.jpg"
   },
   {
    "part": "Bark",
    "title": "(MHNT) Arbutus unedo (bark) .jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:(MHNT)_Arbutus_unedo_(bark)_.jpg",
    "author": "Didier Descouens",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "arbutus-unedo/04-bark.jpg"
   },
   {
    "part": "Habit",
    "title": "The Strawberry Tree (Arbutus unedo) - geograph.org.uk - 1671801.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:The_Strawberry_Tree_(Arbutus_unedo)_-_geograph.org.uk_-_1671801.jpg",
    "author": "David Anstiss",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "arbutus-unedo/05-habit.jpg"
   }
  ],
  "salvia-rosmarinus": [
   {
    "part": "Flowers",
    "title": "Rosmarinus officinalis flowers 01.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Rosmarinus_officinalis_flowers_01.jpg",
    "author": "Syrio",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "salvia-rosmarinus/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Starr-080812-9698-Rosmarinus officinalis-leaves-Makawao-Maui (24298183923).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Starr-080812-9698-Rosmarinus_officinalis-leaves-Makawao-Maui_(24298183923).jpg",
    "author": "Forest and Kim Starr",
    "license": "CC BY 3.0 us",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/us/deed.en",
    "file": "salvia-rosmarinus/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Rosemary Bush (Rosmarinus officinalis) (8346914670).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Rosemary_Bush_(Rosmarinus_officinalis)_(8346914670).jpg",
    "author": "Bernard DUPONT from FRANCE",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "salvia-rosmarinus/03-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "Unidentified Halictidae on Rosmarinus officinalis flowers.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Unidentified_Halictidae_on_Rosmarinus_officinalis_flowers.jpg",
    "author": "Syrio",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "salvia-rosmarinus/04-close-up.jpg"
   }
  ],
  "ginkgo-biloba": [
   {
    "part": "Leaves",
    "title": "Ginkgo biloba - Fallen leaves - 2024 Pisa.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Ginkgo_biloba_-_Fallen_leaves_-_2024_Pisa.jpg",
    "author": "Harlock81",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "file": "ginkgo-biloba/01-leaves.jpg"
   },
   {
    "part": "Fruit",
    "title": "Ginkgo biloba seeds of Hongokuji no Ohatsuki Icho.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Ginkgo_biloba_seeds_of_Hongokuji_no_Ohatsuki_Icho.jpg",
    "author": "さかおり",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "ginkgo-biloba/02-fruit.jpg"
   },
   {
    "part": "Bark",
    "title": "Ginkgo Tree Ginkgo biloba Trunk Bark 2000px.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Ginkgo_Tree_Ginkgo_biloba_Trunk_Bark_2000px.jpg",
    "author": "Photo (c)2007 Derek Ramsey (Ram-Man)",
    "license": "GFDL 1.2",
    "licenseUrl": "http://www.gnu.org/licenses/old-licenses/fdl-1.2.html",
    "file": "ginkgo-biloba/03-bark.jpg"
   },
   {
    "part": "Habit",
    "title": "Ginkgo tree in Green-Wood Cemetery (23299p).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Ginkgo_tree_in_Green-Wood_Cemetery_(23299p).jpg",
    "author": "Rhododendrites",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "ginkgo-biloba/04-habit.jpg"
   },
   {
    "part": "Autumn",
    "title": "A golden Ginkgo biloba in autumn.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:A_golden_Ginkgo_biloba_in_autumn.jpg",
    "author": "Benjamin Ceci",
    "license": "Public domain",
    "licenseUrl": "",
    "file": "ginkgo-biloba/05-autumn.jpg"
   }
  ],
  "cercis-occidentalis": [
   {
    "part": "Flowers",
    "title": "Cercis occidentalis flowers 2004-03-10.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Cercis_occidentalis_flowers_2004-03-10.jpg",
    "author": "No machine-readable author provided. Curtis Clark assumed (based on copyright claims).",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "file": "cercis-occidentalis/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Cercis occidentalis, California.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Cercis_occidentalis,_California.jpg",
    "author": "John Comeau",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "cercis-occidentalis/02-leaves.jpg"
   },
   {
    "part": "Seed pods",
    "title": "H20150416-0002—Cercis occidentalis—RPBG (17051649770).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:H20150416-0002%E2%80%94Cercis_occidentalis%E2%80%94RPBG_(17051649770).jpg",
    "author": "John Rusk from Berkeley, CA, United States of America",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "file": "cercis-occidentalis/03-seed-pods.jpg"
   },
   {
    "part": "Habit",
    "title": "Western red bud near Briceburg 2019-04-14.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Western_red_bud_near_Briceburg_2019-04-14.jpg",
    "author": "LaurentianShield",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "cercis-occidentalis/04-habit.jpg"
   },
   {
    "part": "Bark",
    "title": "Cercis occidentalis bark.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Cercis_occidentalis_bark.jpg",
    "author": "Nadiatalent",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "cercis-occidentalis/05-bark.jpg"
   }
  ],
  "juncus": [
   {
    "part": "Habit",
    "title": "Pitrus plant (Juncus effusus) (1).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Pitrus_plant_(Juncus_effusus)_(1).jpg",
    "author": "Rasbak",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "file": "juncus/01-habit.jpg"
   },
   {
    "part": "Inflorescence",
    "title": "Juncus effusus Sit rozpierzchły Rezerwat przyrody Łazy 2022-06-20 06.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Juncus_effusus_Sit_rozpierzch%C5%82y_Rezerwat_przyrody_%C5%81azy_2022-06-20_06.jpg",
    "author": "Agnieszka Kwiecień, Nova",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "juncus/02-inflorescence.jpg"
   },
   {
    "part": "Stems",
    "title": "Starr 070906-8950 Juncus effusus.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Starr_070906-8950_Juncus_effusus.jpg",
    "author": "Forest &amp; Kim Starr",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "file": "juncus/03-stems.jpg"
   },
   {
    "part": "Close-up",
    "title": "燈心草 Juncus effusus v decipiens -香港花展 Hong Kong Flower Show- (9229895870).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:%E7%87%88%E5%BF%83%E8%8D%89_Juncus_effusus_v_decipiens_-%E9%A6%99%E6%B8%AF%E8%8A%B1%E5%B1%95_Hong_Kong_Flower_Show-_(9229895870).jpg",
    "author": "阿橋 HQ",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "juncus/04-close-up.jpg"
   }
  ],
  "cotinus-coggygria": [
   {
    "part": "Flowers",
    "title": "(MHNT) Cotinus coggygria - inflorescence.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:(MHNT)_Cotinus_coggygria_-_inflorescence.jpg",
    "author": "Didier Descouens",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "cotinus-coggygria/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Cotinus coggygria 'Ancot' (Golden Spirit) Leaves 3008px.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Cotinus_coggygria_%27Ancot%27_(Golden_Spirit)_Leaves_3008px.JPG",
    "author": "Photo by and (c)2006 Derek Ramsey (Ram-Man). Location credit to the Chanticleer Garden.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "file": "cotinus-coggygria/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Cotinus coggygria in Sedovo 4.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Cotinus_coggygria_in_Sedovo_4.jpg",
    "author": "Andrey Butko",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "cotinus-coggygria/03-habit.jpg"
   },
   {
    "part": "Autumn",
    "title": "Cotinus coggygria autumn leaf.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Cotinus_coggygria_autumn_leaf.jpg",
    "author": "Dumi",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "cotinus-coggygria/04-autumn.jpg"
   }
  ],
  "salvia-spathacea": [
   {
    "part": "Flowers",
    "title": "Salvia spathacea.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Salvia_spathacea.JPG",
    "author": "Dvortygirl",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "salvia-spathacea/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Salvia spathacea - Flickr - peganum (3).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Salvia_spathacea_-_Flickr_-_peganum_(3).jpg",
    "author": "peganum from Small Dole, England",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "salvia-spathacea/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Salvia spathacea - Descanso Gardens - La Cañada Flintridge, CA - DSC00853.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Salvia_spathacea_-_Descanso_Gardens_-_La_Ca%C3%B1ada_Flintridge,_CA_-_DSC00853.jpg",
    "author": "Daderot",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "file": "salvia-spathacea/03-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "SAGE, HUMMINGBIRD (salvia spathacea) (4-5-07) 2- canet (535475331).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:SAGE,_HUMMINGBIRD_(salvia_spathacea)_(4-5-07)_2-_canet_(535475331).jpg",
    "author": "ALAN SCHMIERER",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "file": "salvia-spathacea/04-close-up.jpg"
   },
   {
    "part": "Plant",
    "title": "Salvia spathacea - Flickr - peganum (1).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Salvia_spathacea_-_Flickr_-_peganum_(1).jpg",
    "author": "peganum from Small Dole, England",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "salvia-spathacea/05-plant.jpg"
   }
  ],
  "heteromeles-arbutifolia": [
   {
    "part": "Flowers",
    "title": "Heteromeles arbutifolia flowers Wildcat Canyon Preserve 8.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Heteromeles_arbutifolia_flowers_Wildcat_Canyon_Preserve_8.jpg",
    "author": "Awinch1001",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "file": "heteromeles-arbutifolia/01-flowers.jpg"
   },
   {
    "part": "Berries",
    "title": "TOYON (heteromeles arbutifolia) (3-24-07) canet (535371030).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:TOYON_(heteromeles_arbutifolia)_(3-24-07)_canet_(535371030).jpg",
    "author": "ALAN SCHMIERER",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "file": "heteromeles-arbutifolia/02-berries.jpg"
   },
   {
    "part": "Leaves",
    "title": "Heteromeles arbutifolia 2.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Heteromeles_arbutifolia_2.jpg",
    "author": "Unknown",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "heteromeles-arbutifolia/03-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Toyon (Heteromeles arbutifolia) Tree (31892009192).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Toyon_(Heteromeles_arbutifolia)_Tree_(31892009192).jpg",
    "author": "Chris Hunkeler from Carlsbad, California, USA",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "heteromeles-arbutifolia/04-habit.jpg"
   }
  ],
  "baccharis-pilularis": [
   {
    "part": "Flowers",
    "title": "Chaparral Coyote Brush (Baccharis pilularis ssp. consanguinea), Photo 578271695.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Chaparral_Coyote_Brush_(Baccharis_pilularis_ssp._consanguinea),_Photo_578271695.jpg",
    "author": "Cjziems",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "file": "baccharis-pilularis/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Baccharis pilularis.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Baccharis_pilularis.jpg",
    "author": "Unknown",
    "license": "Public domain",
    "licenseUrl": "",
    "file": "baccharis-pilularis/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Baccharis pilularis kz6.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Baccharis_pilularis_kz6.jpg",
    "author": "Krzysztof Ziarnek, Kenraiz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "baccharis-pilularis/03-habit.jpg"
   },
   {
    "part": "Seeds",
    "title": "201211 208 San Diego Botanic Gdn - Natural Coastal Habitat, Baccharis pilularis Coyote Bush, a female plant in seed.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:201211_208_San_Diego_Botanic_Gdn_-_Natural_Coastal_Habitat,_Baccharis_pilularis_Coyote_Bush,_a_female_plant_in_seed.jpg",
    "author": "cultivar413",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "file": "baccharis-pilularis/04-seeds.jpg"
   }
  ],
  "vitis-californica-rogers-red": [
   {
    "part": "Leaves",
    "title": "Vitis californica at Caswell Memorial State Park spring leaves.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Vitis_californica_at_Caswell_Memorial_State_Park_spring_leaves.jpg",
    "author": "Unknown",
    "license": "Public domain",
    "licenseUrl": "",
    "file": "vitis-californica-rogers-red/01-leaves.jpg"
   },
   {
    "part": "Fruit",
    "title": "Vitis californica Roger’s Red ripe grapes.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Vitis_californica_Roger%E2%80%99s_Red_ripe_grapes.jpg",
    "author": "Jengod",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "vitis-californica-rogers-red/02-fruit.jpg"
   },
   {
    "part": "Habit",
    "title": "Vitis californica with grapes.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Vitis_californica_with_grapes.jpg",
    "author": "Unknown",
    "license": "Public domain",
    "licenseUrl": "",
    "file": "vitis-californica-rogers-red/03-habit.jpg"
   },
   {
    "part": "Autumn",
    "title": "201211 094 San Diego Botanic Gdn - Hamilton Children's Garden, Vitis californica California Wild Grape, one of the few natives with autumn color.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:201211_094_San_Diego_Botanic_Gdn_-_Hamilton_Children%27s_Garden,_Vitis_californica_California_Wild_Grape,_one_of_the_few_natives_with_autumn_color.jpg",
    "author": "cultivar413",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "file": "vitis-californica-rogers-red/04-autumn.jpg"
   }
  ],
  "plumbago-auriculata": [
   {
    "part": "Flowers",
    "title": "Flowers of Plumbago auriculata in TBG.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Flowers_of_Plumbago_auriculata_in_TBG.jpg",
    "author": "Miyuki Meinaka",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "plumbago-auriculata/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Starr-090616-0654-Plumbago auriculata-flowers and leaves-Rainbow Park Baldwin Ave-Maui (24870905001).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Starr-090616-0654-Plumbago_auriculata-flowers_and_leaves-Rainbow_Park_Baldwin_Ave-Maui_(24870905001).jpg",
    "author": "Forest and Kim Starr",
    "license": "CC BY 3.0 us",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/us/deed.en",
    "file": "plumbago-auriculata/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Plumbago auriculata-Anna park-yercaud-salem-India.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Plumbago_auriculata-Anna_park-yercaud-salem-India.JPG",
    "author": "Yercaud-elango",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "plumbago-auriculata/03-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "Plumbago auriculata Flower Closeup TorreLaMata.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Plumbago_auriculata_Flower_Closeup_TorreLaMata.jpg",
    "author": "Javier martin",
    "license": "Public domain",
    "licenseUrl": "",
    "file": "plumbago-auriculata/04-close-up.jpg"
   }
  ],
  "melianthus-major": [
   {
    "part": "Leaves",
    "title": "Melianthus major Leaf Top 3008px.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Melianthus_major_Leaf_Top_3008px.jpg",
    "author": "Photo by and (c)2006 Derek Ramsey (Ram-Man). Location credit to the Chanticleer Garden.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "file": "melianthus-major/01-leaves.jpg"
   },
   {
    "part": "Flowers",
    "title": "Giant Honey Flower Melianthus major Newark Park Ozleworth Gloucestershire England.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Giant_Honey_Flower_Melianthus_major_Newark_Park_Ozleworth_Gloucestershire_England.jpg",
    "author": "Acabashi",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "melianthus-major/02-flowers.jpg"
   },
   {
    "part": "Habit",
    "title": "Melianthus major - Orto botanico - Rome, Italy - DSC00098.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Melianthus_major_-_Orto_botanico_-_Rome,_Italy_-_DSC00098.jpg",
    "author": "Daderot",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "file": "melianthus-major/03-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "Melianthus major 2.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Melianthus_major_2.jpg",
    "author": "Stan Shebs",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "melianthus-major/04-close-up.jpg"
   }
  ],
  "diplacus-eleanor": [
   {
    "part": "Flowers",
    "title": "Mimulus pamela.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Mimulus_pamela.jpg",
    "author": "Ruff tuff cream puff",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "file": "diplacus-eleanor/01-flowers.jpg"
   },
   {
    "part": "Habit",
    "title": "Mimulus trish.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Mimulus_trish.jpg",
    "author": "Stickpen",
    "license": "Public domain",
    "licenseUrl": "",
    "file": "diplacus-eleanor/02-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "Sticky Monkey-Flower - Diplacus aurantiacus (43440614412).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Sticky_Monkey-Flower_-_Diplacus_aurantiacus_(43440614412).jpg",
    "author": "Björn S...",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "diplacus-eleanor/03-close-up.jpg"
   },
   {
    "part": "Plant",
    "title": "Sticky Monkey-Flower - Diplacus aurantiacus (42902155992).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Sticky_Monkey-Flower_-_Diplacus_aurantiacus_(42902155992).jpg",
    "author": "Björn S...",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "diplacus-eleanor/04-plant.jpg"
   }
  ],
  "nepeta-walkers-low": [
   {
    "part": "Flowers",
    "title": "Nepeta x faasenii Walkers Low 2zz.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Nepeta_x_faasenii_Walkers_Low_2zz.jpg",
    "author": "Photo by David J. Stang",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "nepeta-walkers-low/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Nepetaxfaassenii.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Nepetaxfaassenii.jpg",
    "author": "Stickpen",
    "license": "Public domain",
    "licenseUrl": "",
    "file": "nepeta-walkers-low/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Nepeta faassenii catmint Easton Lodge Gardens walled garden Little Easton Essex England 01.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Nepeta_faassenii_catmint_Easton_Lodge_Gardens_walled_garden_Little_Easton_Essex_England_01.jpg",
    "author": "Acabashi",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "nepeta-walkers-low/03-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "Nepeta x faassenii Walkers Low 2zz.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Nepeta_x_faassenii_Walkers_Low_2zz.jpg",
    "author": "Photo by David J. Stang",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "nepeta-walkers-low/04-close-up.jpg"
   }
  ],
  "teucrium-fruticans": [
   {
    "part": "Flowers",
    "title": "(MHNT) Teucrium fruticans - Flowers.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:(MHNT)_Teucrium_fruticans_-_Flowers.jpg",
    "author": "Didier Descouens",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "teucrium-fruticans/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Teucrium fruticans L. subsp. fruticans-Germandrée arbustive-Feuilles-20190315.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Teucrium_fruticans_L._subsp._fruticans-Germandr%C3%A9e_arbustive-Feuilles-20190315.jpg",
    "author": "Daniel VILLAFRUELA.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "teucrium-fruticans/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Teucrium fruticans Azureum 1zz.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Teucrium_fruticans_Azureum_1zz.jpg",
    "author": "Photo by David J. Stang",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "teucrium-fruticans/03-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "灌叢石蠶(水果藍) Teucrium fruticans -香港花展 Hong Kong Flower Show- (9198151855).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:%E7%81%8C%E5%8F%A2%E7%9F%B3%E8%A0%B6(%E6%B0%B4%E6%9E%9C%E8%97%8D)_Teucrium_fruticans_-%E9%A6%99%E6%B8%AF%E8%8A%B1%E5%B1%95_Hong_Kong_Flower_Show-_(9198151855).jpg",
    "author": "阿橋 HQ",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "teucrium-fruticans/04-close-up.jpg"
   }
  ],
  "oenothera-lindheimeri": [
   {
    "part": "Flowers",
    "title": "Gaura lindheimeri flower.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Gaura_lindheimeri_flower.JPG",
    "author": "PaleCloudedWhite",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "oenothera-lindheimeri/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Starr-110307-2543-Gaura lindheimeri-leaves-Kula Botanical Garden-Maui (24984958231).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Starr-110307-2543-Gaura_lindheimeri-leaves-Kula_Botanical_Garden-Maui_(24984958231).jpg",
    "author": "Forest and Kim Starr",
    "license": "CC BY 3.0 us",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/us/deed.en",
    "file": "oenothera-lindheimeri/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Gaura lindheimeri A.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Gaura_lindheimeri_A.jpg",
    "author": "Wouter Hagens",
    "license": "Public domain",
    "licenseUrl": "",
    "file": "oenothera-lindheimeri/03-habit.jpg"
   },
   {
    "part": "Flower stem",
    "title": "Gaura lindheimeri Whirling Butterflies 1zz.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Gaura_lindheimeri_Whirling_Butterflies_1zz.jpg",
    "author": "Photo by David J. Stang",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "oenothera-lindheimeri/04-flower-stem.jpg"
   },
   {
    "part": "Close-up",
    "title": "Gaura lindheimeri.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Gaura_lindheimeri.jpg",
    "author": "Gerardgiraud",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "oenothera-lindheimeri/05-close-up.jpg"
   }
  ],
  "salvia-apiana": [
   {
    "part": "Flowers",
    "title": "Salvia apiana 3.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Salvia_apiana_3.jpg",
    "author": "Stan Shebs",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "salvia-apiana/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "J20161110-0061—Salvia apiana—RPBG—DxO (38341671812).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:J20161110-0061%E2%80%94Salvia_apiana%E2%80%94RPBG%E2%80%94DxO_(38341671812).jpg",
    "author": "John Rusk from Berkeley, CA, United States of America",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "file": "salvia-apiana/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Salvia apiana 1c.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Salvia_apiana_1c.JPG",
    "author": "Consultaplantas",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "salvia-apiana/03-habit.jpg"
   },
   {
    "part": "Rosette",
    "title": "Salvia apiana 001 — briweldon.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Salvia_apiana_001_%E2%80%94_briweldon.jpg",
    "author": "Bri Weldon",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "file": "salvia-apiana/04-rosette.jpg"
   }
  ],
  "romneya-coulteri": [
   {
    "part": "Flowers",
    "title": "Romneya coulteri ABL3.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Romneya_coulteri_ABL3.JPG",
    "author": "A. Barra",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "romneya-coulteri/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Romneya coulteri Branche feuillue Jardin des Plantes.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Romneya_coulteri_Branche_feuillue_Jardin_des_Plantes.jpg",
    "author": "Pancrat",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "romneya-coulteri/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Romneya coulteri HRM1.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Romneya_coulteri_HRM1.jpg",
    "author": "A. Barra",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "file": "romneya-coulteri/03-habit.jpg"
   },
   {
    "part": "Buds",
    "title": "Matilija Poppy, Rhomneya coulteri - Flickr - theforestprimeval.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Matilija_Poppy,_Rhomneya_coulteri_-_Flickr_-_theforestprimeval.jpg",
    "author": "JOE BLOWE from Bountiful, Utah, Iran",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "romneya-coulteri/04-buds.jpg"
   },
   {
    "part": "Close-up",
    "title": "Romneya-coulteri-flower.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Romneya-coulteri-flower.jpg",
    "author": "Sten Porse",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "romneya-coulteri/05-close-up.jpg"
   }
  ],
  "scabiosa-columbaria": [
   {
    "part": "Flowers",
    "title": "Scabiosa columbaria0.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Scabiosa_columbaria0.jpg",
    "author": "Kurt Stüber [1]",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "file": "scabiosa-columbaria/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Scabiosa columbaria Driakiew gołębia 2020-08-07 04.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Scabiosa_columbaria_Driakiew_go%C5%82%C4%99bia_2020-08-07_04.jpg",
    "author": "Agnieszka Kwiecień, Nova",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "scabiosa-columbaria/02-leaves.jpg"
   },
   {
    "part": "Basal rosette",
    "title": "GBIF 2888802 5995451240.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:GBIF_2888802_5995451240.jpg",
    "author": "Styrelsen for Grøn Arealomlægning og Vandmiljø/The Danish Agency for Green Land Use and Aquatic Environment (SGAV)",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "file": "scabiosa-columbaria/03-basal-rosette.jpg"
   },
   {
    "part": "Habit",
    "title": "Small scabious (Scabiosa columbaria) - geograph.org.uk - 5489110.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Small_scabious_(Scabiosa_columbaria)_-_geograph.org.uk_-_5489110.jpg",
    "author": "Evelyn Simak",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "scabiosa-columbaria/04-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "Scabiosa columbaria flower.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Scabiosa_columbaria_flower.jpg",
    "author": "PatriciaVNes",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "scabiosa-columbaria/05-close-up.jpg"
   }
  ],
  "salvia-pozo-blue": [
   {
    "part": "Flowers",
    "title": "Salvia clevelandii - jim sage - desc-flowers - status-rare.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Salvia_clevelandii_-_jim_sage_-_desc-flowers_-_status-rare.jpg",
    "author": "Unknown",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "file": "salvia-pozo-blue/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Salvia clevelandii 'Allen Chickering' Leaves 3264px.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Salvia_clevelandii_%27Allen_Chickering%27_Leaves_3264px.jpg",
    "author": "Photo by and (c)2006 Derek Ramsey (Ram-Man). Location credit to the Chanticleer Garden.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "file": "salvia-pozo-blue/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "210624 033 San Diego Botanic Gdn - Dickinson Family Conservatory, Salvia clevelandii x leucophylla 'Allen Chickering', Delosperma sp Ice Plant, Felicia amelloides.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:210624_033_San_Diego_Botanic_Gdn_-_Dickinson_Family_Conservatory,_Salvia_clevelandii_x_leucophylla_%27Allen_Chickering%27,_Delosperma_sp_Ice_Plant,_Felicia_amelloides.jpg",
    "author": "cultivar413",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "file": "salvia-pozo-blue/03-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "Salvia clevelandii 4371.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Salvia_clevelandii_4371.jpg",
    "author": "Buendia22",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "salvia-pozo-blue/04-close-up.jpg"
   }
  ],
  "salvia-mellifera": [
   {
    "part": "Flowers",
    "title": "Salvia mellifera flowers 2003-03-12.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Salvia_mellifera_flowers_2003-03-12.jpg",
    "author": "No machine-readable author provided. Curtis Clark assumed (based on copyright claims).",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "file": "salvia-mellifera/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "File--i-Salvia mellifera-i--br--Mint family (Lamiaceae) (f5e142ee-c13e-5458-2b5f-492e1394435f).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:File--i-Salvia_mellifera-i--br--Mint_family_(Lamiaceae)_(f5e142ee-c13e-5458-2b5f-492e1394435f).jpg",
    "author": "NPS",
    "license": "Public domain",
    "licenseUrl": "",
    "file": "salvia-mellifera/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Salvia mellifera kz01.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Salvia_mellifera_kz01.jpg",
    "author": "Krzysztof Ziarnek, Kenraiz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "salvia-mellifera/03-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "Black Sage (Salvia mellifera) (2322427355).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Black_Sage_(Salvia_mellifera)_(2322427355).jpg",
    "author": "Jerry Kirkhart from Los Osos, Calif.",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "file": "salvia-mellifera/04-close-up.jpg"
   }
  ],
  "salvia-yangii": [
   {
    "part": "Flowers",
    "title": "Mint and Perovskia (8009159019).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Mint_and_Perovskia_(8009159019).jpg",
    "author": "Amanda Slater from Coventry, West Midlands, UK",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "salvia-yangii/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Perovskia atriplicifolia leave.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Perovskia_atriplicifolia_leave.jpg",
    "author": "Doronenko",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "file": "salvia-yangii/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Gommern, der Heidegarten, Perovskia atriplicifolia.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Gommern,_der_Heidegarten,_Perovskia_atriplicifolia.jpg",
    "author": "Dguendel",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "file": "salvia-yangii/03-habit.jpg"
   },
   {
    "part": "Flower spikes",
    "title": "20170719Perovskia atriplicifolia3.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:20170719Perovskia_atriplicifolia3.jpg",
    "author": "AnRo0002",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "file": "salvia-yangii/04-flower-spikes.jpg"
   },
   {
    "part": "Close-up",
    "title": "Perovskia-atriplicifolia-2.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Perovskia-atriplicifolia-2.jpg",
    "author": "Sten Porse",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "salvia-yangii/05-close-up.jpg"
   }
  ],
  "verbena-bonariensis": [
   {
    "part": "Flowers",
    "title": "Verbena bonariensis, bloeiwijze. 28-08-2021. (d.j.b) 01.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Verbena_bonariensis,_bloeiwijze._28-08-2021._(d.j.b)_01.jpg",
    "author": "Dominicus Johannes Bergsma",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "verbena-bonariensis/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Verbena bonariensis 'Purple top' (Verbenaceae) leaves.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Verbena_bonariensis_%27Purple_top%27_(Verbenaceae)_leaves.JPG",
    "author": "Magnus Manske",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "file": "verbena-bonariensis/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "'Verbena bonariensis' in the Walled Garden at Goodnestone Park Kent England 1.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:%27Verbena_bonariensis%27_in_the_Walled_Garden_at_Goodnestone_Park_Kent_England_1.jpg",
    "author": "Acabashi",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "verbena-bonariensis/03-habit.jpg"
   },
   {
    "part": "Stem",
    "title": "Verbena bonariensis stem (02).jpeg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Verbena_bonariensis_stem_(02).jpeg",
    "author": "Leon Perrie",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "file": "verbena-bonariensis/04-stem.jpg"
   }
  ],
  "anigozanthos": [
   {
    "part": "Flowers",
    "title": "Starr-090430-6847-Anigozanthos flavidus-flowers-Enchanting Floral Gardens of Kula-Maui (24322840644).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Starr-090430-6847-Anigozanthos_flavidus-flowers-Enchanting_Floral_Gardens_of_Kula-Maui_(24322840644).jpg",
    "author": "Forest and Kim Starr",
    "license": "CC BY 3.0 us",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/us/deed.en",
    "file": "anigozanthos/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Anigozanthos rufus 'Red Kangaroo Paw' (Haemodoraceae) leaves.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Anigozanthos_rufus_%27Red_Kangaroo_Paw%27_(Haemodoraceae)_leaves.JPG",
    "author": "Magnus Manske",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "anigozanthos/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Anigozanthos flavidus HRM.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Anigozanthos_flavidus_HRM.jpg",
    "author": "Cillas",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "anigozanthos/03-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "Anigozanthos flavidus flower stalk - HNT.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Anigozanthos_flavidus_flower_stalk_-_HNT.jpg",
    "author": "Eric Polk",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "anigozanthos/04-close-up.jpg"
   }
  ],
  "eschscholzia-californica": [
   {
    "part": "Flowers",
    "title": "Bright Orange California Poppy.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Bright_Orange_California_Poppy.jpg",
    "author": "Rojer Wisner",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "file": "eschscholzia-californica/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Eschscholzia californica (California poppy) florescence and leaves next to Calystegia soldanella (beach morningglory) leaves (7184134380).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Eschscholzia_californica_(California_poppy)_florescence_and_leaves_next_to_Calystegia_soldanella_(beach_morningglory)_leaves_(7184134380).jpg",
    "author": "oliveoligarchy from California, United States",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "file": "eschscholzia-californica/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Eschscholzia californica 'alifornian poppy' (Papaveraceae) plant and leaves.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Eschscholzia_californica_%27alifornian_poppy%27_(Papaveraceae)_plant_and_leaves.JPG",
    "author": "Magnus Manske",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "eschscholzia-californica/03-habit.jpg"
   },
   {
    "part": "Seeds",
    "title": "Eschscholzia californica seeds.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Eschscholzia_californica_seeds.jpg",
    "author": "Steve Hurst @ USDA-NRCS PLANTS Database",
    "license": "Public domain",
    "licenseUrl": "",
    "file": "eschscholzia-californica/04-seeds.jpg"
   },
   {
    "part": "Mass bloom",
    "title": "California Poppies blossom - Antelope Valley California Poppy Reserve4.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:California_Poppies_blossom_-_Antelope_Valley_California_Poppy_Reserve4.jpg",
    "author": "Tracie Hall",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "eschscholzia-californica/05-mass-bloom.jpg"
   }
  ],
  "nemophila-menziesii": [
   {
    "part": "Flowers",
    "title": "Flowers of Nemophila menziesii in Nokonoshima Island Park.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Flowers_of_Nemophila_menziesii_in_Nokonoshima_Island_Park.jpg",
    "author": "そらみみ",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "nemophila-menziesii/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Baby Blue Eyes Scanography.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Baby_Blue_Eyes_Scanography.jpg",
    "author": "Osnat Ravid Amir",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "file": "nemophila-menziesii/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Baby Blue Eyes, Shell Creek (49621100262).jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Baby_Blue_Eyes,_Shell_Creek_(49621100262).jpg",
    "author": "Peter D. Tillman from USA",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "file": "nemophila-menziesii/03-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "Nemophila menziesii.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Nemophila_menziesii.jpg",
    "author": "Sureshbup",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "nemophila-menziesii/04-close-up.jpg"
   }
  ],
  "layia-platyglossa": [
   {
    "part": "Flowers",
    "title": "Layia platyglossa 'Tidy Tips' (Compositae) flower.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Layia_platyglossa_%27Tidy_Tips%27_(Compositae)_flower.JPG",
    "author": "Magnus Manske",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "layia-platyglossa/01-flowers.jpg"
   },
   {
    "part": "Leaves",
    "title": "Layia platyglossa 'Tidy Tips' (Compositae) leaves.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Layia_platyglossa_%27Tidy_Tips%27_(Compositae)_leaves.JPG",
    "author": "Magnus Manske",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "layia-platyglossa/02-leaves.jpg"
   },
   {
    "part": "Habit",
    "title": "Layia platyglossa 'Tidy Tips' (Compositae) plant.JPG",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Layia_platyglossa_%27Tidy_Tips%27_(Compositae)_plant.JPG",
    "author": "Magnus Manske",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "file": "layia-platyglossa/03-habit.jpg"
   },
   {
    "part": "Close-up",
    "title": "Tidy Tips (Layia platyglossa) flower.jpg",
    "pageUrl": "https://commons.wikimedia.org/wiki/File:Tidy_Tips_(Layia_platyglossa)_flower.jpg",
    "author": "Alan Vernon",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "file": "layia-platyglossa/04-close-up.jpg"
   }
  ]
 }
};
